sorting issue #30
protontypes/climate-triage pull request #38
Opened 2024-03-04 16:15 UTC by milanych

2024-03-04 16:34 UTC, Codeshark-NET requested changes
Hey @milanych! Thank you kindly for adressing this issue 🙌 Overall the code looks good, and I'll go ahead and test it once the changes in this review have been adapted. Please use pnpm to follow the existing project structure. 👍 Thanks!

Update: You may also want to merge lastest commit on `main` 👍

2024-03-04 17:37 UTC, milanych commented on .husky/pre-commit
> -pnpm lint
Hi, I am sorry to say that, but pull request seems to be the hardest part of this issue 🤦‍♂️
I've edited the pre-commit file to what it was before, and deleted package-lock, but...

If I try `git add .`, nothing happens.
If I try `git commit -m 'pr fixes'` it says something like 
```
C:\Users\username\AppData\Roaming\npm/node_modules/node/bin/node: line 1: This: command not found
husky - command not found in PATH=...
```
CONTRIBUTING.md literally says to do simple add and commit.

Sorry, this is the first "serious" pr, bear with me.
**So, what do I really need to do?**

2024-03-04 17:56 UTC, Codeshark-NET commented on .husky/pre-commit
> -pnpm lint
Don't be sorry - we all start somewhere. 😊

Your challenge may be a bit specific to your system, but here's a few things you can check:
- Make sure you have pnpm installed (you can install it globally via npm)
- Ensure that you added `pnpm lint` and `pnpm test` to the `pre-commit` file (you can test them both manually in your terminal to see if they fail or not)

Husky, in this case, is used as a pre-commit check, which runs those commands, before "allowing you" to commit. It's sort of like a safety check, to make sure that code commited is linted (and now with your addition, tested).

If the `pnpm test` addition is giving you problems, just don't include it for now.

2024-03-05 10:26 UTC, milanych commented
@Codeshark-NET Morning, I finally fixed this Husky issue for my Win10. Hope everything is good now.

2024-03-05 10:27 UTC, Codeshark-NET commented
> @Codeshark-NET Morning, I finally fixed this Husky issue for my Win10. Hope everything is good now.

Looks good @milanych , thanks! I'll test it out when I get a chance, and approve if everything is good. 👍

2024-03-05 12:10 UTC, merged

2024-03-05 13:14 UTC, Codeshark-NET commented
Congrats on your first PR @milanych 🙌 I ran "prettier" on the code, to fix the linting errors, but otherwise great. 👍 Thanks a lot!

2024-03-05 13:20 UTC, Ly0n commented
@Codeshark-NET @milanych I just realise that the "By project Age" filter is lost. :worried: . Any reason this was removed? I think this filter is relevant because some people want to contribute to a new project rather than fixing old ones.

2024-03-05 14:10 UTC, milanych commented
@Codeshark-NET We have now 3 filters: by Age, by Downloads, and by Stars. What do you mean?

![image](https://github.com/protontypes/climate-triage/assets/19264511/35ec3f5f-180a-4ade-bd4f-0e571fd54e3e)

2024-03-05 14:23 UTC, Codeshark-NET commented
The age there is the "most recent issues", I think @Ly0n is referring to the project age. Maybe we open a new issue to get that merged back in, if you're interested in doing that too @milanych :-)

2024-03-05 14:33 UTC, milanych commented
So we need 4 buttons, right? "Recent", "Age", "Downloads", "Stars" ?

2024-03-05 14:52 UTC, Codeshark-NET commented
> So we need 4 buttons, right? "Recent", "Age", "Downloads", "Stars" ?

Yes that sounds right 👍

2024-03-05 14:52 UTC, Ly0n commented
I'm not sure if a new user will be able to understand these shortened versions. Maybe recent issues, project age, downloads and stars?